// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web; // <--- Cambio clave: ahora retorna 'web' en lugar de error
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // AQUÍ PUSE TU CONFIGURACIÓN DE WEB
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNujB5pbWAeWKsObn9vOpI-Za3DhanwoU',
    appId: '1:434950088211:web:b10bf8fd009ff12f0841e6',
    messagingSenderId: '434950088211',
    projectId: 'bodytech-pruebas',
    authDomain: 'bodytech-pruebas.firebaseapp.com',
    storageBucket: 'bodytech-pruebas.firebasestorage.app',
    measurementId: 'G-3C1GRJWRJ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtLSqWY6cl91upX4BCZHPC6JPvFC05NO0',
    appId: '1:434950088211:android:6f07931bbf4fbdee0841e6',
    messagingSenderId: '434950088211',
    projectId: 'bodytech-pruebas',
    storageBucket: 'bodytech-pruebas.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAn9UEsIGXMJpfITFjgg8MVc9jjLd0ro-k',
    appId: '1:434950088211:ios:6272c6704d25c7e80841e6',
    messagingSenderId: '434950088211',
    projectId: 'bodytech-pruebas',
    storageBucket: 'bodytech-pruebas.firebasestorage.app',
    iosBundleId: 'com.example.bodytechPrueba',
  );
}